language: node_js
node_js:
- '0.12'
addons:
  sauce_connect: true
before_install:
- npm install npm -g
# - npm install -g run-browser
# - npm install -g phantomjs --phantomjs_cdnurl=http://cnpmjs.org/downloads
- npm install -g zuul
before_script:
- npm install
# - npm install istanbul coveralls
script: npm run-script travis-test


env:
  global:
    - secure: JxhiVqt3Uf/HNukmKJdC8tFqoOKg3OLC8aHQrkfkWW7AVcDVnvnikX1DYivVkplklKTdzOaxy9GTfKgwAHvIW/EZVf++//ryr0E26bbFnlzRyxWcDykPHf5B7Cp6plkby0YcJ8POMQjlQJm6AO4T4XF6BwNAmvhWHqU8Z+FLBMJ9yRLTayxOsEf7btoWbA05fuZI7kL8n0URxI4NWja1oYMYm10hsMJNvS8kLEjTVC0Uu8pRuscgO0W2ji1xXluFvZ1Mckx4Gch/eYYjvB3+cyLYmmvdZzn7VCMrwni07KxHJ/E/+OFRuKvTDKygVMjeHliXp0QzsmseBPXyavihkdJisvnvKUym9cD254MqrF4TT9RT/iOMYWD2GKodTZrnL5riar88BXXfYtlwb0kq91zcUmOWRxzlqM4iWqFzH/E4KKZvX/aut0YDILwVogQOi4iu09H/9fNnYBQz5D5cn8xIEtyRARDf9hLaudMQyp6yl1m8LU5ZFgim2M9Nw17M9+voWQkVOYlCH8f62Ymb8vefNBaWxA4JPCNjU/B+QFH4VDClb2WIjXDhcMkPaYDG5VhPscPTAdn1niWdc1gDAQjoH5MQNAaX7zXZwAA5aNNxkWA+GfYWLMN3uRKEzQICU5WWKuMItoGK/2wBYdng4HHH+nHSVdeYZdIUO0gQtV0=
    - secure: FAAthfXROyefJLZ38GxsUe1tO6+TYFKgmkk7NvzAWbyG7CMkd+xr4wOVfsrjJf1QLgq577h839DdnGRjSx7OiQ4VJ8EoB8NRgbAqoZSPO6dYaNHnqaZcvoAFwJWSJ7WYA7FzHHKIPuPbom7KKoL2bHklNDdnmuqRW8Bjf7BomifkACiGymSqlhvDNyD0usXzRnKYGFivqaX9ZgOI0qBHFg0hTkH8gXjIm81GpBJNtEwROpDkAukADMMfJ0SquzIq4vN4RqZfkhteMj7a+WYEvd5XpoTBPcdjjlivmmtamW98/mxofFCEzCICkDov9U4ggdgGWVSSkpqtpVCJHyKstWR9UyB5tApyd/+N1CsXZgvXDJjlO2lbHqdcSImvcE87rX/gMQU2PD6JtnUOeAa0dTWsHOenzVztIcYUySWl13CMd44GeuIosWMDkHEfvklPrKHv4dDS1aQCc/7hZufb+S/cmUFdEh/cxeovovpzqY+Q9ri0799u1bFghXAo0EiOfx/tB7KkSaVReF3UgcOjX9bTCVyxxcn5NFLF4ECpL9NaV46ToWogLYFOBi6JsrB9sEWBXt/eFKPymTofr7wioTPCapvEdp75mKWKNZMc313ECj9rccnI/lNVkS2gDxe3O1bRYiaHQVl6IW7CFjXSZEwkcym+uszDUJYuhKG45ck=